runtime: go
api_version: go1.9
module: slackbot

handlers:
- url: /.*
  script: _go_app
  secure: always

env_variables:
  SLACK_SIGNING_SECRET: <your-signing-secret>
  SLACK_BOT_TOKEN: <your-bot-token>